version: '3.8'
  services:
    traefik:
      image: traefik:v2.10.4
      restart: always
      container_name: traefik
      command:
        - --log.level=ERROR
        - --api=true
        - --api.insecure=true
        - --ping=true
        - --accesslog=true
        - --providers.docker.endpoint=unix:///var/run/docker.sock
        - --providers.docker.exposedbydefault=false
        - --providers.docker.network=my_app
        - --entrypoints.http.address=:80
        - --entrypoints.https.address=:443
        - --metrics.prometheus=true
        - --entryPoints.metrics.address=:8082
        - --metrics.prometheus.entryPoint=metrics
        - --certificatesresolvers.mycert.acme.email=cert@mecan.ir
        - --certificatesresolvers.mycert.acme.storage=/acme/acme.json
        - --certificatesresolvers.mycert.acme.tlschallenge=true
      ports:
        - 80:80
        - 443:443
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - traefik-acme:/acme
      labels:
      - traefik.enable=true
      - traefik.docker.network=my_app
      - traefik.http.routers.traefik.middlewares=https-redirect
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.rule=Host(``)
      - traefik.http.routers.traefik-secure.entrypoints=https
      - traefik.http.routers.traefik-secure.rule=Host(``)
      - traefik.http.routers.traefik-secure.tls=true
      - traefik.http.routers.traefik-secure.tls.options=default
      - traefik.http.routers.traefik-secure.tls.certresolver=mycert
      - traefik.http.routers.traefik-secure.service=traefik
      - traefik.http.services.traefik.loadbalancer.server.port=8080


        
